uHospitalizable=?
#UNHANDLED: true,true,true,true,true,false
uEmergency=?
#UNHANDLED: true,true,false,false
uAge=18.0
#MIN: 18.0 INCLUSIVE / MAX: 18.0 EXCLUSIVE
uPreviouslyHospitalized=?
#UNHANDLED: true,true,false
pRequiredLaboratoryTests=?
#UNHANDLED: false,true,false,true
pRequiredDiagnosticTests=?
#UNHANDLED: false,true,false,true
pClinicalConditions=negative
#ENUM: negative,positive,negative,positive
PreAnestheticEvaluation=?
#UNHANDLED: PreAnestheticEvaluation=true,PreAnestheticEvaluation=false
AdverseEvents=present
#ENUM: present,absent / UNHANDLED: AdverseEvents=true,AdverseEvents=false
uInformedConsent=absent
#ENUM: absent,present
nPreoperationalChecklist=incomplete
#ENUM: incomplete,complete
ICU=?
#UNHANDLED: ICU=true
rAldreteScore=8.0
#MIN: 8.0 INCLUSIVE / MAX: 8.0 EXCLUSIVE
rActivity=1.0
#MIN: 0.0 EXCLUSIVE
rCirculation=1.0
#MIN: 0.0 EXCLUSIVE
rConsciousness=1.0
#MIN: 0.0 EXCLUSIVE
rO2Saturation=1.0
#MIN: 0.0 EXCLUSIVE
rRespiration=1.0
#MIN: 0.0 EXCLUSIVE
