uHospitalizable=true
#ENUM: true,false
uEmergency=true
#ENUM: true,false
uAge=18.0
#MIN: 18.0 INCLUSIVE / MAX: 18.0 EXCLUSIVE
uPreviouslyHospitalized=true
#ENUM: true,false
pRequiredLaboratoryTests=true
#ENUM: false,true
pRequiredDiagnosticTests=true
#ENUM: false,true
pClinicalConditions=positive
#ENUM: negative,positive
AdverseEvents=present
#ENUM: absent,present
uInformedConsent=present
#ENUM: absent,present
nPreoperationalChecklist=complete
#ENUM: incomplete,complete
ICU=false
#ENUM: true
rAldreteScore=8.0
#MIN: 8.0 INCLUSIVE / MAX: 8.0 EXCLUSIVE
rActivity=1.0
#MIN: 0.0 EXCLUSIVE
rCirculation=1.0
#MIN: 0.0 EXCLUSIVE
rConsciousness=1.0
#MIN: 0.0 EXCLUSIVE
rO2Saturation=1.0
#MIN: 0.0 EXCLUSIVE
rRespiration=1.0
#MIN: 0.0 EXCLUSIVE
